version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
